name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    name: build
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        os:
            - ubuntu-latest
              #- macos-latest
              #- windows-latest
        ocaml-compiler:
            - '5.1'

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@main
        with:
          submodules: true
    
      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true
          allow-prerelease-opam: true

      - run: opam install -t batrpc batrpc-otel --deps-only
      - run: opam exec -- dune build @install --ignore-promoted-rules
      - run: opam exec -- dune runtest --ignore-promoted-rules

      - run: opam install trace trace-tef mtime
      - run: opam exec -- dune build @install @runtest --ignore-promoted-rules

      - run: opam install ocaml-protoc
      - run: opam exec -- dune build @genproto

      # check that nothing changed
      - run: git diff --exit-code

